import '@nrp/tailwind-preset';
import { ThemeProvider } from '@nrp/components';
import { Container, Header } from '@nrp/components/server';
import { ReactNode } from 'react';
import { cn } from '@nrp/utils';
import { Inter as FontSans } from 'next/font/google';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata = {
  title: 'Welcome to blog',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header
            items={[
              { title: 'Home', url: '/', exact: true },
              { title: 'Posts', url: '/posts' },
            ]}
          />
          <Container>{children}</Container>
        </ThemeProvider>
      </body>
    </html>
  );
}
